name: 'gz_dbt_repository'
version: '1.0.0'
config-version: 2
profile: 'default'

models:
  gz_dbt_repository:
    +materialized: view  # Tout sera en view par défaut
    marts:
      finance:
        +materialized: table  # Sauf les modèles dans marts/finance
        +schema: finance       # Cela ira dans le dataset `dbt_tonprenom_finance`
