
name: 'gz_dbt_repository'
version: '1.0.0'
config-version: 2   # <-- version du format du fichier YAML
profile: 'default'

models:
  gz_dbt_repository:
    marts:
      +materialized: table  # Matérialisation par défaut pour tous les modèles dans mart

# D'autres configurations peuvent être ajoutées ici
