name: 'gz_dbt_repository'
version: '1.0.0'
config-version: 2   # <-- version du format du fichier YAML
profile: 'default'

models:
  gz_dbt_repository:
    marts:
      +materialized: view  # Tous les modèles dans "marts" seront des vues
    staging:
      +materialized: view  # Tous les modèles dans "staging" seront des vues
    intermediate:
      +materialized: view  # Tous les modèles dans "intermediate" seront des vues
    finance:
      +materialized: table  # Le modèle "finance" sera en table
      +schema: finance  # Schéma spécifique pour "finance" (optionnel)
