version: 2

sources:
  - name: raw           # alias de ton dataset dans DBT
    database: symmetric-curve-452216-p4  # remplace par ton vrai ID GCP
    schema: gz_raw_data       # nom réel du dataset
    tables:
      - name: sales
        identifier: raw_gz_sales

              # Freshness testing - make sure to fill in the ...
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after: { count: 90, period: day }

      - name: product
        identifier: raw_gz_product

      - name: ship
        identifier: raw_gz_ship

models:
      - name: stg_raw__sales
        description: Sales of Greenweez / we have one row per product_id found in each orders_id
        columns:
          - name: date_date
            description: Date of purchase
          - name: orders_id
            description: Unique identifier of the order
          - name: products_id
            description: ID of the product purchased
          - name: revenue
            description: Revenue generated from the sale
          - name: quantity
            description: Number of units sold
        tests:
           - unique:
               column_name: "(orders_id || '-' || products_id)"

      - name: stg_raw__product
        description: List of all products sold by Greenweez. Primary Key
        columns:
          - name: products_id
            description: ID of the product purchased.
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: Price of the product at the time of purchase.

      - name: stg_raw__ship
        description: Shipping details for each order.
        columns:
          - name: orders_id
            description: Unique identifier for each order in the shipping process.
            tests:
             - unique
             - not_null
          - name: shipping_fee
            description: Fee charged for the shipping of the product.
          - name: logCost
            description: The cost associated with the shipment (logistics).
          - name: ship_cost
            description: Cost of shipping, will be cast to the appropriate data type in the model.
